// This file is generated by Sapper — do not edit it!
export const routes = [
	{ pattern: /^\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "_" */ '../../routes/index.html') },
	{ pattern: /^\/register\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "register" */ '../../routes/register/index.html') },
	{ pattern: /^\/settings\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "settings" */ '../../routes/settings/index.html') },
	{ pattern: /^\/article(?:\/([^\/]+?))?\/?$/, params: match => ({ slug: match[1] }), load: () => import(/* webpackChunkName: "article_$slug$" */ '../../routes/article/[slug].html') },
	{ pattern: /^\/editor(?:\/([^\/]+?))?\/?$/, params: match => ({ slug: match[1] }), load: () => import(/* webpackChunkName: "editor_$slug$" */ '../../routes/editor/[slug].html') },
	{ pattern: /^\/login\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "login" */ '../../routes/login/index.html') },
	{ pattern: /^\/auth\/register\/?$/, ignore: true },
	{ pattern: /^\/auth\/logout\/?$/, ignore: true },
	{ pattern: /^\/auth\/login\/?$/, ignore: true },
	{ pattern: /^\/auth\/save\/?$/, ignore: true },
	{ pattern: /^\/auth\/user\/?$/, ignore: true },
	{ pattern: /^(?:\/([^\/]+?)(?:\/([^\/]+?))?)?\/?$/, params: match => ({ user: match[1], view: match[2] }), load: () => import(/* webpackChunkName: "$user$_$view$" */ '../../routes/[user]/[view].html') }
];

if (module.hot) {
	import('/Users/208311/Development/SVELTE/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}