// This file is generated by Sapper — do not edit it!
export const timestamp = 1527544197438;

export const assets = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];

export const shell = [
	"client/89506c3e7ddb202d90c1/0.0.js",
	"client/89506c3e7ddb202d90c1/$user$_$view$.$user$_$view$.js",
	"client/89506c3e7ddb202d90c1/_._.js",
	"client/89506c3e7ddb202d90c1/article_$slug$.article_$slug$.js",
	"client/89506c3e7ddb202d90c1/editor_$slug$.editor_$slug$.js",
	"client/89506c3e7ddb202d90c1/login.login.js",
	"client/89506c3e7ddb202d90c1/$user$_$view$~_.$user$_$view$~_.js",
	"client/89506c3e7ddb202d90c1/main.js",
	"client/89506c3e7ddb202d90c1/register.register.js",
	"client/89506c3e7ddb202d90c1/settings.settings.js",
	"client/89506c3e7ddb202d90c1/vendors~article_$slug$.vendors~article_$slug$.js",
	"client/89506c3e7ddb202d90c1/vendors~article_$slug$~editor_$slug$.vendors~article_$slug$~editor_$slug$.js"
];

export const routes = [
	
];